// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentTest.Data;

#nullable disable

namespace StudentTest.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251023024155_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentTest.Models.MstStudent", b =>
                {
                    b.Property<int>("StudentKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StudentKey"));

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SubjectKey")
                        .HasColumnType("integer");

                    b.HasKey("StudentKey");

                    b.HasIndex("SubjectKey");

                    b.ToTable("MstStudents");
                });

            modelBuilder.Entity("StudentTest.Models.MstSubject", b =>
                {
                    b.Property<int>("SubjectKey")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubjectKey"));

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("SubjectKey");

                    b.ToTable("MstSubjects");
                });

            modelBuilder.Entity("StudentTest.Models.MstStudent", b =>
                {
                    b.HasOne("StudentTest.Models.MstSubject", "Subject")
                        .WithMany("MsStudent")
                        .HasForeignKey("SubjectKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("StudentTest.Models.MstSubject", b =>
                {
                    b.Navigation("MsStudent");
                });
#pragma warning restore 612, 618
        }
    }
}
